services:
  backend-service:
    depends_on:
      - mongodb-service
    build: .
    ports:
      - 4000:4000
    # environment:
    # Disable since we don't use mongod. Using mongodb-atlas via .env
    #   - MONGODB_URI=mongodb://mongodb-service:27017/imagex
  mongodb-service:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
