services:
  backend-service:
    build: .
    ports:
      - 4000:4000
  mongodb-service:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
